import pytest
from backend.app.schemas import QuoteRequest, Territory, TelematicsRisk, Severity, FloodZone, VehicleCategory, ValuationType, UsageType, NCDPercentage
from backend.app.engine import generate_quote
from backend.app.config import SCORECARD_VERSION

test_cases = [
    # MEDIUM Risk, Policy: MV-0001
    ({'driver_age': 35, 'traffic_violations': 0, 'telematics_risk': 'Low', 'gender': 'M', 'years_licensed': '5+ years', 'occupation': 'Professional/Exec', 'previous_claims_3yr': '0 claims', 'ncd_percentage': 0.0, 'prior_claims_count': 1, 'average_prior_severity': 'Low', 'fault_profile': 'Not at fault', 'fraud_indicators': 'None', 'territory': 'Urban (KL, Selangor, Penang, Johor)', 'flood_zone': 'Low', 'crime_rate': 'Low', 'road_type': 'Highway primary', 'seasonal_risk': 'Year-round', 'vehicle_value': 34000.0, 'engine_capacity': 1300, 'vehicle_category': 'Private Car', 'valuation_type': 'Market Value', 'vehicle_age': 8, 'modification_status': 'Stock/standard', 'safety_features': 'ADAS, AEB, ESC', 'tyre_condition': 'New/good', 'annual_mileage': 15000, 'usage_type': 'Commercial', 'parking_night': 'Garaged', 'annual_trips': '<5,000', 'immobiliser': 'Factory fitted', 'gps_tracking': 'Active tracking', 'alarm_system': 'OEM alarm', 'excess_chosen': 'High (>1,000)', 'named_drivers': '1 (owner only)', 'policy_lapse_history': 'No lapse', 'sum_insured_accuracy': 'Accurate', 'premium_payment': 'Annual full', 'windscreen_cover': False, 'ncd_protector': False, 'special_perils_cover': False}, 1900.0, 285.0),
    # LOW Risk, Policy: MV-0002
    ({'driver_age': 64, 'traffic_violations': 0, 'telematics_risk': 'Low', 'gender': 'M', 'years_licensed': '5+ years', 'occupation': 'Professional/Exec', 'previous_claims_3yr': '0 claims', 'ncd_percentage': 0.0, 'prior_claims_count': 0, 'average_prior_severity': 'Low', 'fault_profile': 'Not at fault', 'fraud_indicators': 'None', 'territory': 'Urban (KL, Selangor, Penang, Johor)', 'flood_zone': 'Low', 'crime_rate': 'Low', 'road_type': 'Highway primary', 'seasonal_risk': 'Year-round', 'vehicle_value': 23000.0, 'engine_capacity': 1332, 'vehicle_category': 'Private Car', 'valuation_type': 'Market Value', 'vehicle_age': 1, 'modification_status': 'Stock/standard', 'safety_features': 'ADAS, AEB, ESC', 'tyre_condition': 'New/good', 'annual_mileage': 15000, 'usage_type': 'Private', 'parking_night': 'Garaged', 'annual_trips': '<5,000', 'immobiliser': 'Factory fitted', 'gps_tracking': 'Active tracking', 'alarm_system': 'OEM alarm', 'excess_chosen': 'High (>1,000)', 'named_drivers': '1 (owner only)', 'policy_lapse_history': 'No lapse', 'sum_insured_accuracy': 'Accurate', 'premium_payment': 'Annual full', 'windscreen_cover': False, 'ncd_protector': False, 'special_perils_cover': False}, 700.0, 105.0),
    # MEDIUM Risk, Policy: MV-0003
    ({'driver_age': 50, 'traffic_violations': 0, 'telematics_risk': 'Low', 'gender': 'F', 'years_licensed': '5+ years', 'occupation': 'Professional/Exec', 'previous_claims_3yr': '0 claims', 'ncd_percentage': 0.0, 'prior_claims_count': 0, 'average_prior_severity': 'Low', 'fault_profile': 'Not at fault', 'fraud_indicators': 'None', 'territory': 'Urban (KL, Selangor, Penang, Johor)', 'flood_zone': 'Low', 'crime_rate': 'Low', 'road_type': 'Highway primary', 'seasonal_risk': 'Year-round', 'vehicle_value': 26000.0, 'engine_capacity': 1498, 'vehicle_category': 'Private Car', 'valuation_type': 'Market Value', 'vehicle_age': 4, 'modification_status': 'Stock/standard', 'safety_features': 'ADAS, AEB, ESC', 'tyre_condition': 'New/good', 'annual_mileage': 15000, 'usage_type': 'Private', 'parking_night': 'Garaged', 'annual_trips': '<5,000', 'immobiliser': 'Factory fitted', 'gps_tracking': 'Active tracking', 'alarm_system': 'OEM alarm', 'excess_chosen': 'High (>1,000)', 'named_drivers': '1 (owner only)', 'policy_lapse_history': 'No lapse', 'sum_insured_accuracy': 'Accurate', 'premium_payment': 'Annual full', 'windscreen_cover': False, 'ncd_protector': False, 'special_perils_cover': False}, 770.0, 115.5),
    # LOW Risk, Policy: MV-0009
    ({'driver_age': 44, 'traffic_violations': 0, 'telematics_risk': 'Low', 'gender': 'F', 'years_licensed': '5+ years', 'occupation': 'Professional/Exec', 'previous_claims_3yr': '0 claims', 'ncd_percentage': 0.0, 'prior_claims_count': 0, 'average_prior_severity': 'Low', 'fault_profile': 'Not at fault', 'fraud_indicators': 'None', 'territory': 'Urban (KL, Selangor, Penang, Johor)', 'flood_zone': 'Low', 'crime_rate': 'Low', 'road_type': 'Highway primary', 'seasonal_risk': 'Year-round', 'vehicle_value': 30000.0, 'engine_capacity': 1300, 'vehicle_category': 'Private Car', 'valuation_type': 'Market Value', 'vehicle_age': 7, 'modification_status': 'Stock/standard', 'safety_features': 'ADAS, AEB, ESC', 'tyre_condition': 'New/good', 'annual_mileage': 15000, 'usage_type': 'Private', 'parking_night': 'Garaged', 'annual_trips': '<5,000', 'immobiliser': 'Factory fitted', 'gps_tracking': 'Active tracking', 'alarm_system': 'OEM alarm', 'excess_chosen': 'High (>1,000)', 'named_drivers': '1 (owner only)', 'policy_lapse_history': 'No lapse', 'sum_insured_accuracy': 'Accurate', 'premium_payment': 'Annual full', 'windscreen_cover': False, 'ncd_protector': False, 'special_perils_cover': False}, 1300.0, 195.0),
    # HIGH Risk, Policy: MV-0016
    ({'driver_age': 28, 'traffic_violations': 0, 'telematics_risk': 'Low', 'gender': 'F', 'years_licensed': '5+ years', 'occupation': 'Professional/Exec', 'previous_claims_3yr': '0 claims', 'ncd_percentage': 0.0, 'prior_claims_count': 1, 'average_prior_severity': 'Low', 'fault_profile': 'Not at fault', 'fraud_indicators': 'None', 'territory': 'Urban (KL, Selangor, Penang, Johor)', 'flood_zone': 'Low', 'crime_rate': 'Low', 'road_type': 'Highway primary', 'seasonal_risk': 'Year-round', 'vehicle_value': 31000.0, 'engine_capacity': 1300, 'vehicle_category': 'Private Car', 'valuation_type': 'Market Value', 'vehicle_age': 0, 'modification_status': 'Stock/standard', 'safety_features': 'ADAS, AEB, ESC', 'tyre_condition': 'New/good', 'annual_mileage': 15000, 'usage_type': 'Private', 'parking_night': 'Garaged', 'annual_trips': '<5,000', 'immobiliser': 'Factory fitted', 'gps_tracking': 'Active tracking', 'alarm_system': 'OEM alarm', 'excess_chosen': 'High (>1,000)', 'named_drivers': '1 (owner only)', 'policy_lapse_history': 'No lapse', 'sum_insured_accuracy': 'Accurate', 'premium_payment': 'Annual full', 'windscreen_cover': False, 'ncd_protector': False, 'special_perils_cover': False}, 1400.0, 210.0),
    # HIGH Risk, Policy: MV-0027
    ({'driver_age': 29, 'traffic_violations': 0, 'telematics_risk': 'Low', 'gender': 'F', 'years_licensed': '5+ years', 'occupation': 'Manual/Delivery', 'previous_claims_3yr': '0 claims', 'ncd_percentage': 0.0, 'prior_claims_count': 0, 'average_prior_severity': 'Low', 'fault_profile': 'Not at fault', 'fraud_indicators': 'None', 'territory': 'Urban (Other)', 'flood_zone': 'Low', 'crime_rate': 'Low', 'road_type': 'Highway primary', 'seasonal_risk': 'Year-round', 'vehicle_value': 14000.0, 'engine_capacity': 1332, 'vehicle_category': 'Private Car', 'valuation_type': 'Market Value', 'vehicle_age': 1, 'modification_status': 'Stock/standard', 'safety_features': 'ADAS, AEB, ESC', 'tyre_condition': 'New/good', 'annual_mileage': 15000, 'usage_type': 'Private', 'parking_night': 'Garaged', 'annual_trips': '<5,000', 'immobiliser': 'Factory fitted', 'gps_tracking': 'Active tracking', 'alarm_system': 'OEM alarm', 'excess_chosen': 'High (>1,000)', 'named_drivers': '1 (owner only)', 'policy_lapse_history': 'No lapse', 'sum_insured_accuracy': 'Accurate', 'premium_payment': 'Annual full', 'windscreen_cover': False, 'ncd_protector': False, 'special_perils_cover': False}, 560.0, 84.0),
]

@pytest.mark.parametrize("req_dict, expected_premium, tolerance", test_cases)
def test_real_policies(req_dict, expected_premium, tolerance):
    req = QuoteRequest(**req_dict)
    res = generate_quote(req)
    
    assert res["scorecard_version"] == SCORECARD_VERSION
    
    actual_premium = res["premium_breakdown"]["total_payable"]
    variance = abs(actual_premium - expected_premium)
    variance_pct = (variance / expected_premium) * 100
    
    tolerance_strict = expected_premium * 0.15
    
    if variance > tolerance_strict:
        pytest.fail(
            f"Engine off by {variance_pct:.1f}% (Variance RM {variance:.2f} vs expected RM {expected_premium:.2f}). "
            f"Failed fixed 15% threshold."
        )
